apiVersion: v1
kind: Pod
metadata:
  name: sample3
spec:
  containers:
   - name: debug
     image: centos:7
    ## Command is nothing but overwriting ENTRYPOINT
     command:
      - sleep
      - "100000"
   - name: ping
     image: swathipottabathini/zs-ping
      args:
       - "yahoo.com"