---
apiVersion: v1
kind: Pod
metadata:
  name: dev-pod
  namespace: dev
spec:
  containers:
    - name: centos
      image: centos:7
      command:
        - sleep
        - "10000000"
---
apiVersion: v1
kind: Pod
metadata:
  name: prod-pod
  namespace: prod
spec:
  containers:
    - name: nginx
      image: nginx
